{{- if not .Values.nginx.existingConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openarchiefbeheer.nginxFullname" . }}
  labels:
    {{- include "openarchiefbeheer.nginxLabels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name  {{ .Values.settings.allowedHosts  | replace "," " "}} localhost;

      location ~ ^/admin|oidc|static|assets|api/ {
        proxy_pass http://{{ include "openarchiefbeheer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }};
        proxy_pass_header Server;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_redirect off;
        proxy_pass_request_headers on;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
      }

      location /_health/ {
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log error;
          return 200 'OK';
      }

      location / {
          try_files $uri $uri/ /static/frontend/index.html;
      }
    }
{{- end }}
